<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GradeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('grades')->insert([
            [
                'quartile' => '1',
                'course_name' => 'Programme and Career Orientation',
                'test_name' => 'Assessment',
                'lowest_passing_grade' => 5.5,
                'ec' => 2.5,
                'best_grade' => 9.3,
                'class' => 'inprogress',
                'passed_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '1',
                'course_name' => 'Computer Science Basics',
                'test_name' => 'Written Exam',
                'lowest_passing_grade' => 5.5,
                'ec' => 5,
                'best_grade' => 9.3,
                'class' => 'inprogress',
                'passed_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '1',
                'course_name' => 'Programming Basics',
                'test_name' => 'Case Study',
                'lowest_passing_grade' => 5.5,
                'ec' => 5,
                'best_grade' => 10.0,
                'class' => 'inprogress',
                'passed_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '2',
                'course_name' => 'Object Orientated Programming',
                'test_name' => 'Case Study	',
                'lowest_passing_grade' => 5.5,
                'ec' => 5,
                'best_grade' => 7.0,
                'class' => 'inprogress',
                'passed_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '2',
                'course_name' => 'Object Orientated Programming',
                'test_name' => 'Project',
                'lowest_passing_grade' => 5.5,
                'ec' => 5,
                'best_grade' => 8.5,
                'class' => 'inprogress',
                'passed_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '3',
                'course_name' => 'Framework Development 1',
                'test_name' => 'Case Study',
                'lowest_passing_grade' => 5.5,
                'ec' => 5,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '3',
                'course_name' => 'Framework Project 1',
                'test_name' => 'Project',
                'lowest_passing_grade' => 5.5,
                'ec' => 2.5,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '3',
                'course_name' => 'Framework Project 1',
                'test_name' => 'Assessment',
                'lowest_passing_grade' => 5.5,
                'ec' => 2.5,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '3',
                'course_name' => 'Framework Project 1',
                'test_name' => 'Report',
                'lowest_passing_grade' => 5.5,
                'ec' => 2.5,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '4',
                'course_name' => 'Framework Project 2',
                'test_name' => 'Portfolio',
                'lowest_passing_grade' => 5.5,
                'ec' => 3,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '4',
                'course_name' => 'Framework Project 2',
                'test_name' => 'Project',
                'lowest_passing_grade' => 5.5,
                'ec' => 3,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => '4',
                'course_name' => 'Framework Project 2',
                'test_name' => 'Assessment',
                'lowest_passing_grade' => 5.5,
                'ec' => 4,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => 'All',
                'course_name' => 'Personal Professional Development',
                'test_name' => 'Portfolio',
                'lowest_passing_grade' => 5.5,
                'ec' => 12.5,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => 'All',
                'course_name' => 'IT Personality 1',
                'test_name' => 'Portfolio',
                'lowest_passing_grade' => 5.5,
                'ec' => 1.25,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'quartile' => 'All',
                'course_name' => 'IT Personality 2',
                'test_name' => 'Portfolio',
                'lowest_passing_grade' => 5.5,
                'ec' => 1.25,
                'best_grade' => null,
                'class' => 'inprogress',
                'passed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
